In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,32,7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr1=np.array([[3,6,37,7]],np.int64)

In [5]:
myarr1[0,1]

6

In [6]:
myarr1.shape

(1, 4)

In [7]:
myarr1.dtype

dtype('int64')

In [8]:
myarr1[0,1]=45

In [9]:
myarr1

array([[ 3, 45, 37,  7]], dtype=int64)

# Array creation: 
### 1) Conversion from other python structures (eg. lists,tuples)

In [10]:
l=np.array([[1,2,3],[5,4,3],[2,4,3]])

In [12]:
l

array([[1, 2, 3],
       [5, 4, 3],
       [2, 4, 3]])

In [13]:
l.dtype

dtype('int32')

In [14]:
l.shape

(3, 3)

In [15]:
l.size

9

In [16]:
np.array({3,4,5})

array({3, 4, 5}, dtype=object)

### 2) Intrinsic numpy array creation objects (eg. arange,ones,zeros,etc)

In [18]:
zeros=np.zeros((3,2))

In [19]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
zeros.shape

(3, 2)

In [21]:
zeros.size

6

In [22]:
zeros.dtype

dtype('float64')

In [24]:
rng=np.arange(15)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
lspace=np.linspace(1,5,12)

In [28]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
lsp=np.linspace(1,4,4)

In [30]:
lsp

array([1., 2., 3., 4.])

In [31]:
emp=np.empty((4,6))

In [32]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60218491e-306, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.86921279e-306, 8.90098127e-307, 1.78020848e-306],
       [1.60219035e-306, 1.42418172e-306, 2.04712906e-306,
        7.56589622e-307, 1.11258277e-307, 8.90111708e-307]])

In [34]:
  emp_like=np.empty_like(lspace)

In [35]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [36]:
ide=np.identity(45)

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
ide.shape

(45, 45)

In [39]:
arr=np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr=arr.reshape(3,33)

In [44]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [46]:
arr=arr.ravel()

In [47]:
arr.shape

(99,)

In [48]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [49]:
ar=np.array(x)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.sum(axis=0)

array([12,  8,  9])

In [52]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [53]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [54]:
ar.flat

In [55]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [56]:
ar.ndim

2

In [57]:
ar.size

9

In [58]:
 ar.nbytes

36

In [59]:
one=np.array([1,3,2,234,4])

In [60]:
one.argmax()

3

In [61]:
one.argmin()

0

In [62]:
one.argsort()

array([0, 2, 1, 4, 3], dtype=int64)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar.argmin()

8

In [65]:
ar.argmax()

6

In [66]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [67]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [68]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [69]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [70]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [71]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [72]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [73]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [74]:
ar2=np.array([[2,1,3],[4,2,1],[3,5,4]])

In [75]:
ar2

array([[2, 1, 3],
       [4, 2, 1],
       [3, 5, 4]])

In [76]:
ar+ar2

array([[ 3,  3,  6],
       [ 8,  7,  7],
       [10,  6,  4]])

In [77]:
ar*ar2

array([[ 2,  2,  9],
       [16, 10,  6],
       [21,  5,  0]])

In [78]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [79]:
ar.sum()

29

In [80]:
ar.max()

7

In [81]:
ar.min()

0

In [82]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [83]:
type(np.where(ar>5))

tuple

In [84]:
np.count_nonzero(ar)

8

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [86]:
ar[1,2]=0

In [87]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [88]:
import sys

In [89]:
py_ar=[3,1,5,6]

In [94]:
np_ar=np.array(py_ar)

In [95]:
sys.getsizeof(1)*len(py_ar)

112

In [96]:
np_ar.itemsize * np_ar.size

16